-- MySQL Script generated by MySQL Workbench
-- Sun Nov  6 20:34:55 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rfd_local
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Country` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Country` (
  `country_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(2) NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000000;

SHOW WARNINGS;
CREATE UNIQUE INDEX `unq_ctry_code` ON `Country` (`code` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `unq_ctry_name` ON `Country` (`name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `City` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `City` (
  `city_id` BIGINT UNSIGNED NOT NULL,
  `country_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`city_id`),
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `Country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_city_cntry_idx` ON `City` (`country_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `unq_city_cntry` ON `City` (`name` ASC, `country_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Building` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Building` (
  `building_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`building_id`),
  CONSTRAINT `fk_Building_City1`
    FOREIGN KEY (`city_id`)
    REFERENCES `City` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_bldng_city_idx` ON `Building` (`city_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `unq_bldng_city` ON `Building` (`city_id` ASC, `name` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Location` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Location` (
  `location_id` BIGINT UNSIGNED NOT NULL,
  `city_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(45) NOT NULL,
  `country_id` BIGINT UNSIGNED NULL,
  `building_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`location_id`),
  CONSTRAINT `fk_Location_City`
    FOREIGN KEY (`city_id`)
    REFERENCES `City` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_Country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `Country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_Building1`
    FOREIGN KEY (`building_id`)
    REFERENCES `Building` (`building_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_loc_city_idx` ON `Location` (`city_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_loc_cntry_idx` ON `Location` (`country_id` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `unq_loc_name` ON `Location` (`name` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_loc_bldng_idx` ON `Location` (`building_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Person` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Person` (
  `person_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000000;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ContractType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ContractType` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ContractType` (
  `contract_type_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(1) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`contract_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000000;

SHOW WARNINGS;
CREATE UNIQUE INDEX `code_UNIQUE` ON `ContractType` (`code` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Resource` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Resource` (
  `resource_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `person_id` BIGINT UNSIGNED NOT NULL,
  `billRate` DECIMAL(6,2) NULL,
  `location_id` BIGINT UNSIGNED NULL,
  `contract_type_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`resource_id`),
  CONSTRAINT `fk_resource_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `Person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `Location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_contracttype1`
    FOREIGN KEY (`contract_type_id`)
    REFERENCES `ContractType` (`contract_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000000;

SHOW WARNINGS;
CREATE INDEX `fk_res_per_idx` ON `Resource` (`person_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_resource_location1_idx` ON `Resource` (`location_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_resource_contracttype1_idx` ON `Resource` (`contract_type_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `LocationRate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LocationRate` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `LocationRate` (
  `location_id` BIGINT UNSIGNED NOT NULL,
  `contract_type_id` BIGINT UNSIGNED NOT NULL,
  `rate` DECIMAL(6,2) NULL,
  `location_rate_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`location_rate_id`),
  CONSTRAINT `fk_locationrate_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `Location` (`location_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locationrate_contracttype1`
    FOREIGN KEY (`contract_type_id`)
    REFERENCES `ContractType` (`contract_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000000;

SHOW WARNINGS;
CREATE INDEX `fk_locationrate_location1_idx` ON `LocationRate` (`location_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_locationrate_contracttype1_idx` ON `LocationRate` (`contract_type_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `ContractType`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `ContractType` (`contract_type_id`, `code`, `description`) VALUES (1, 'M', 'Managed Service');
INSERT INTO `ContractType` (`contract_type_id`, `code`, `description`) VALUES (2, 'C', 'Contractor');
INSERT INTO `ContractType` (`contract_type_id`, `code`, `description`) VALUES (3, 'P', 'Permanent');

COMMIT;

