-- MySQL Script generated by MySQL Workbench
-- Thu Sep 29 14:15:46 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rfd_local
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rfd_local
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rfd_local` DEFAULT CHARACTER SET utf8 ;
USE `rfd_local` ;

-- -----------------------------------------------------
-- Table `rfd_local`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rfd_local`.`Country` ;

CREATE TABLE IF NOT EXISTS `rfd_local`.`Country` (
  `country_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(2) NULL,
  PRIMARY KEY (`country_id`),
  UNIQUE INDEX `unq_ctry_code` (`code` ASC),
  UNIQUE INDEX `unq_ctry_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000000;


-- -----------------------------------------------------
-- Table `rfd_local`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rfd_local`.`City` ;

CREATE TABLE IF NOT EXISTS `rfd_local`.`City` (
  `city_id` BIGINT UNSIGNED NOT NULL,
  `country_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_city_cntry_idx` (`country_id` ASC),
  UNIQUE INDEX `unq_city_cntry` (`name` ASC, `country_id` ASC),
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `rfd_local`.`Country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rfd_local`.`Building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rfd_local`.`Building` ;

CREATE TABLE IF NOT EXISTS `rfd_local`.`Building` (
  `building_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`building_id`),
  INDEX `fk_bldng_city_idx` (`city_id` ASC),
  UNIQUE INDEX `unq_bldng_city` (`city_id` ASC, `name` ASC),
  CONSTRAINT `fk_Building_City1`
    FOREIGN KEY (`city_id`)
    REFERENCES `rfd_local`.`City` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rfd_local`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rfd_local`.`Location` ;

CREATE TABLE IF NOT EXISTS `rfd_local`.`Location` (
  `location_id` BIGINT UNSIGNED NOT NULL,
  `city_id` BIGINT UNSIGNED NULL,
  `name` VARCHAR(45) NOT NULL,
  `country_id` BIGINT UNSIGNED NULL,
  `building_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`location_id`),
  INDEX `fk_loc_city_idx` (`city_id` ASC),
  INDEX `fk_loc_cntry_idx` (`country_id` ASC),
  UNIQUE INDEX `unq_loc_name` (`name` ASC),
  INDEX `fk_loc_bldng_idx` (`building_id` ASC),
  CONSTRAINT `fk_Location_City`
    FOREIGN KEY (`city_id`)
    REFERENCES `rfd_local`.`City` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_Country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `rfd_local`.`Country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_Building1`
    FOREIGN KEY (`building_id`)
    REFERENCES `rfd_local`.`Building` (`building_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
